language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

services:
  - mongodb

before_script:
  - mongo mongo_test --eval 'db.createUser({user:"mongo_client", pwd:"qwerty1234", roles:["readWrite"]});'