language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mongodb

before_script:
  - phpenv config-add myconfig.ini
  - composer install

script: phpunit --configuration phpunit.xml